### PR TITLE
Fix armel build

### LINKED ISSUE #23: dpf-plugins 1.6 armel build fails on debian sid: "Error: selected processor does not support `vmrs r3,fpscr' in ARM mode"
Heya :)

there is an build error with dpf-plugins 1.6 on armel:

```
{standard input}: Assembler messages:
{standard input}:202446: Error: selected processor does not support `vmrs r3,fpscr' in ARM mode
{standard input}:202448: Error: selected processor does not support `vmsr fpscr,r3' in ARM mode
```

A full log is here: https://buildd.debian.org/status/fetch.php?pkg=dpf-plugins&arch=armel&ver=1.6%2Bds-1&stamp=1671548666&raw=0

### PR DESCRIPTION
**Pull request by snd1**
This fixes #23 :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by falkTX** [comment]
wow I wonder if anyone actually uses them...

in any case, please remove the surrounding parenthesis, it is not needed in C/C++ compiler macros, just leave `if defined(x) && !defined(y)`

**Comment by snd1** [comment]
Oops ok, one moment. There is a pizza in the stove...

Well, it's still a official arch on debian, so i try to support this.

**Comment by falkTX** [comment]
Actually, dont mind it. I need to push the fix first into DPF, then it propagates to DPF-Plugins and other DPF things.
Will do this manually, no worries

**Comment by falkTX** [comment]
Handled on DPF side, this repo was just updated.
Thanks!

**Pull request closed without merging**
